export const USER_ROLE = {
  ADMIN: "ROLE_ADMIN",
  PROJECT_OWNER: "ROLE_PO",
  DEVELOP: "ROLE_DEV"
};

export const ERRORS = {
  ACCOUNT_PERMISSION: "Account don't have permission",
  NETWORK: "Network Error"
};

export const STATUS = {
  INTERESTED: "Interested",
  MATCHING: "Matching",
  NOT_INTERESTED: "Refused"
};

export const STATUS_COLLABORATE = {
  NOT_COLLABORATE: "NOT_COLLABORATE",
  USER_REQUEST_COLLABORATE: "USER_REQUEST_COLLABORATE",
  PROJECT_REQUEST_COLLABORATE: "PROJECT_REQUEST_COLLABORATE",
  COLLABORATING: "COLLABORATING",
  USER_REJECT_COLLABORATE: "USER_REJECT_COLLABORATE",
  PROJECT_REJECT_COLLABORATE: "PROJECT_REJECT_COLLABORATE"
};

export const STATUS_COLLABORATE_FIREBASE = {
  COLLABORATE: 0,
  COLLABORATING: 1,
  COLLABORATED: 2
};

export const COLOR_THREE_SELECTION = ["#07BD24", "#DF12CA", "#df7112"];
export const COLOR_ONE_SELECTION = ["#75726A"];
export const COLOR_INTERESTED = "#0F7D3E";
export const COLOR_MATCHING = "#FFD166";
export const COLOR_REFUSED = "#ff0000";
